name: pump_failure_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - flask
  - pip:
    - fastapi
    - uvicorn
    - azureml-core
    - azureml-defaults