name: pump_failure_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - flask
  - pip
  - pip:
    - feature_engine
    - fastapi
    - uvicorn
    - azureml-defaults
    - azureml-core
