name: preprocessing_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - pip
  - pip:
    - feature-engine
    - azureml-defaults
    - azureml-core
    - azureml-dataset-runtime