name: training_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-optimize
  - lightgbm
  - pip
  - pip:
    - azureml-defaults
    - azureml-core
    - azureml-dataset-runtime
    - azure-storage-blob
